slogan: "Yet another bootstrap theme."

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Catwarrior
    url: https://github.com/catwarrior/catwarrior.github.io
    intro: "Catwarrior's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: https://github.com/catwarrior
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/stephan
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.pn
duoshuo_shortname: catwarrior

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR